-- AlterTable
ALTER TABLE `postulantes` ADD COLUMN `banco` VARCHAR(100) NULL,
    ADD COLUMN `conoce_detenido_entorno` BOOLEAN NULL,
    ADD COLUMN `conoce_detenido_motivo` VARCHAR(255) NULL,
    ADD COLUMN `detenido_motivo` VARCHAR(255) NULL,
    ADD COLUMN `deudas_motivo` VARCHAR(255) NULL,
    ADD COLUMN `hipoteca_institucion` VARCHAR(150) NULL,
    ADD COLUMN `hipoteca_monto` DECIMAL(10, 2) NULL,
    ADD COLUMN `hipoteca_motivo` VARCHAR(255) NULL,
    ADD COLUMN `ingresos_adicionales` BOOLEAN NULL,
    ADD COLUMN `ingresos_adicionales_monto` DECIMAL(10, 2) NULL,
    ADD COLUMN `ingresos_adicionales_motivo` VARCHAR(255) NULL,
    ADD COLUMN `numero_cuenta_bancaria` VARCHAR(50) NULL,
    ADD COLUMN `otra_deuda_institucion` VARCHAR(150) NULL,
    ADD COLUMN `otra_deuda_monto` DECIMAL(10, 2) NULL,
    ADD COLUMN `otra_deuda_motivo` VARCHAR(255) NULL,
    ADD COLUMN `otras_deudas` BOOLEAN NULL,
    ADD COLUMN `procesado_motivo` VARCHAR(255) NULL,
    ADD COLUMN `tiene_cuenta_bancaria` BOOLEAN NULL,
    ADD COLUMN `tiene_hipotecas` BOOLEAN NULL,
    ADD COLUMN `tipo_cuenta_bancaria` VARCHAR(50) NULL;
